### ISSUE TITLE
Error on loading dataset

### ISSUE THREAD

**Issue by fcoavc** [FranciscoAriel/wnr#1]
After install the package, I can´t load dataset  `device`

````R
library(wnr)
data(device)
````
Output:

>Warning message:
> In data(device) : data set ‘device’ not found

**Comment by FranciscoAriel** [comment]
Thanks @fcoavc 

The bug has been solved, see [3a3b9e1](https://github.com/FranciscoAriel/wnr/commit/3a3b9e1110b4805d841f2616771f81548fb7d968).
